# Generated by Django 3.2.20 on 2023-07-17 08:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('text', models.TextField(default='А еще я ем траву')),
                ('category', models.CharField(choices=[('tank', 'танк'), ('heal', 'лечитель'), ('damage-diler', 'дд'), ('gilde-master', 'гилдмастер'), ('merchant', 'барыга'), ('quest-giver', 'квестгивер'), ('smith', 'кузнец'), ('tanner', 'кожевенник'), ('potion-maker', 'зельевар'), ('spell-master', 'маг')], default='smith', max_length=12)),
                ('upload', models.ImageField(blank=True, null=True, upload_to='media/images/')),
                ('date_in', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='Нету отзыва')),
                ('status', models.BooleanField(default=False)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bu_bo_app.article')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
