# Generated by Django 3.2.20 on 2023-07-17 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bu_bo_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='upload',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
